Config		= [ ServerBlock ]

ServerBlock = 'server' '{' [ ServerParam ] '}'
ServerParam = 		BlockValueServer
				|	ErrorPageParam
				|	LocationBlock

BlockValueServer		= KeyServer '=' value ';'
KeyServer = 'listen' | 'server_name' | 'error_log' | 'access_log' | 'root' | 'index' | 'autoindex' | 'host'

LocationBlock = 'location' value '{' [ LocationParam ] '}'
LocationParam =		BlockValueLocation
				|	ErrorPageParam
				|	DenyMethodParam

BlockValueLocation		= KeyLocation '=' value ';'
KeyLocation = 'root' | 'index' | 'autoindex' | 'return'


ErrorPageParam	= 'error_page' '='  error_code | [ error_code ',' ] ':' value ';'
DenyMethodParam	= 'deny_method' '=' method | [ method ',' ] ';'

value 		= [a-zA-Z0-9/._-]+
