name: Compile

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install cmake
        uses: sudo apt-get install cmake

      - name: Create build dir
        uses: mkdir -p build

      - name: Run Cmake
        uses: |
          cmake -B build
          cmake --build build --target WebServ