name: Unit Test

on:
  push:
    branches:
      - main
      - devlop
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - devlop
      - feature/*
      - hotfix/*

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install php-cgi

      - name: Make test
        run: make test

      - name: Run Test
        run: ./run_tests.sh all -y